### ISSUE TITLE
formatting slightly different after parsing

### ISSUE THREAD

**Issue by cstanislawski** [cstanislawski/helm-valgrade#19]
some of the comments are 2 spaces less indented & some newlines are missing, snippet from the current output:

```yaml
kubeVersionOverride: ""
## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd

## Install Prometheus Operator CRDs
##
crds:
  enabled: true
## custom Rules to override "for" and "severity" in defaultRules
##
customRules: {}
# AlertmanagerFailedReload:
#   for: 3m
# AlertmanagerMembersInconsistent:
#   for: 5m
#   severity: "warning"
```

expected:
```yaml
kubeVersionOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd

## Install Prometheus Operator CRDs
##
crds:
  enabled: true

## custom Rules to override "for" and "severity" in defaultRules
##
customRules: {}
  # AlertmanagerFailedReload:
  #   for: 3m
  # AlertmanagerMembersInconsistent:
  #   for: 5m
  #   severity: "warning"
```

tested with versions:
kube-prometheus-stack:
58.5.2 -> 58.7.0
61.3.0 -> 61.7.2
