### ISSUE TITLE
[bug] misplaced keys in output

### ISSUE THREAD

**Issue by cstanislawski** [cstanislawski/helm-valgrade#21]
when using valgrade some of the keys are misplaced compared to the original/base target version values file

target base values file:
```yaml
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      ## Service account for Prometheus Operator Webhook Job Patch to use.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
      ##
      serviceAccount:
        create: true
        automountServiceAccountToken: true
    # Security context for create job container
```

valgrade's output:
```yaml
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccount:
        automountServiceAccountToken: true
        create: true
    # Security context for create job container
```

this does not cause any issues, as the generated manifests are working as expected, but this introduces unnecessary differences confusing the users

this is also different from https://github.com/cstanislawski/helm-valgrade/issues/19
